FROM node:20-alpine AS deps

ARG DATABASE_URL
ARG BETTER_AUTH_URL
ARG BETTER_AUTH_SECRET
ARG NEXT_PUBLIC_SITE_URL
ARG INTERNAL_BACKEND_BASE_URL
ARG REDIS_URL
ARG OTP_DELIVERY_STATUS_TTL_SECONDS
ARG OTP_DELIVERY_STATUS_KEY_PREFIX
ARG PURELYMAIL_SMTP_HOST
ARG PURELYMAIL_SMTP_PORT
ARG PURELYMAIL_SMTP_USER
ARG PURELYMAIL_SMTP_PASSWORD
ARG PURELYMAIL_FROM_EMAIL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET

ENV NEXT_TELEMETRY_DISABLED=1
ENV DATABASE_URL=$DATABASE_URL
ENV BETTER_AUTH_URL=$BETTER_AUTH_URL
ENV BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV INTERNAL_BACKEND_BASE_URL=$INTERNAL_BACKEND_BASE_URL
ENV REDIS_URL=$REDIS_URL
ENV OTP_DELIVERY_STATUS_TTL_SECONDS=$OTP_DELIVERY_STATUS_TTL_SECONDS
ENV OTP_DELIVERY_STATUS_KEY_PREFIX=$OTP_DELIVERY_STATUS_KEY_PREFIX
ENV PURELYMAIL_SMTP_HOST=$PURELYMAIL_SMTP_HOST
ENV PURELYMAIL_SMTP_PORT=$PURELYMAIL_SMTP_PORT
ENV PURELYMAIL_SMTP_USER=$PURELYMAIL_SMTP_USER
ENV PURELYMAIL_SMTP_PASSWORD=$PURELYMAIL_SMTP_PASSWORD
ENV PURELYMAIL_FROM_EMAIL=$PURELYMAIL_FROM_EMAIL
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm build

EXPOSE 3001

CMD ["pnpm", "start"]
